{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:OCC.Display.backend:backend loaded: qt-pyqt5\n",
      "INFO:OCC.Display.SimpleGui:GUI backend set to: qt-pyqt5\n"
     ]
    }
   ],
   "source": [
    "from OCC.BRepFeat import BRepFeat_Gluer\n",
    "from OCC.BRepPrimAPI import BRepPrimAPI_MakeBox\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.LocOpe import LocOpe_FindEdges\n",
    "from OCC.TopAbs import TopAbs_FACE\n",
    "from OCC.TopExp import TopExp_Explorer\n",
    "from OCC.TopLoc import TopLoc_Location\n",
    "from OCC.TopoDS import topods_Face\n",
    "from OCC.gp import gp_Pnt, gp_Trsf, gp_Vec\n",
    "\n",
    "from core_geometry_utils import center_boundingbox\n",
    "\n",
    "display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "\n",
    "\n",
    "def get_faces(_shape):\n",
    "    \"\"\" return the faces from `_shape`\n",
    "    :param _shape: TopoDS_Shape, or a subclass like TopoDS_Solid\n",
    "    :return: a list of faces found in `_shape`\n",
    "    \"\"\"\n",
    "    topExp = TopExp_Explorer()\n",
    "    topExp.Init(_shape, TopAbs_FACE)\n",
    "    _faces = []\n",
    "\n",
    "    while topExp.More():\n",
    "        fc = topods_Face(topExp.Current())\n",
    "        _faces.append(fc)\n",
    "        topExp.Next()\n",
    "\n",
    "    return _faces\n",
    "\n",
    "\n",
    "def tag_faces(_shape, _color, shape_name):\n",
    "    \"\"\" tag the faces of a shape\n",
    "    in this example, this easy to see which faces of the 2 shapes we need to glue together\n",
    "    so by reading the tagged faces, its easy to find the correct index for the\n",
    "    list `facesA` (5) and `facesB` (4)\n",
    "    :param _shape: the shape to tag\n",
    "    :param color: a string, to colors the faces the `_shape` we're exploring\n",
    "    :param shape_name: name to tag the faces the `_shape`\n",
    "    \"\"\"\n",
    "    for n, f in enumerate(_shape):\n",
    "        # centroid of the face\n",
    "        center_pt = center_boundingbox(f)\n",
    "        # displays the face in the viewer\n",
    "        display.DisplayShape(f, color=_color, transparency=0.9)\n",
    "        # tag the face in the viewer\n",
    "        display.DisplayMessage(center_pt, \"{0}_nr_{1}\".format(shape_name, n))\n",
    "\n",
    "\n",
    "def tag_edge(_edge, msg, _color=(1, 0, 0)):\n",
    "    \"\"\" tag an edge\n",
    "    \"\"\"\n",
    "    pt = center_boundingbox(_edge)\n",
    "    display.DisplayMessage(pt, msg, None, _color, False)\n",
    "\n",
    "\n",
    "def glue_solids(event=None):\n",
    "    display.EraseAll()\n",
    "    display.Context.RemoveAll()\n",
    "    # Without common edges\n",
    "    S1 = BRepPrimAPI_MakeBox(gp_Pnt(500., 500., 0.), gp_Pnt(100., 250., 300.)).Shape()\n",
    "    facesA = get_faces(S1)\n",
    "    tag_faces(facesA, \"BLUE\", \"facesA\")\n",
    "\n",
    "    # the face to glue\n",
    "    F1 = facesA[5]\n",
    "\n",
    "    S2 = BRepPrimAPI_MakeBox(gp_Pnt(400., 400., 300.), gp_Pnt(200., 300., 500.)).Shape()\n",
    "    facesB = get_faces(S2)\n",
    "\n",
    "    tag_faces(facesB, \"GREEN\", \"facesB\")\n",
    "\n",
    "    # the face to glue of the opposite shape\n",
    "    F2 = facesB[4]\n",
    "\n",
    "    # perform glueing operation\n",
    "    glue1 = BRepFeat_Gluer(S2, S1)\n",
    "    glue1.Bind(F2, F1)\n",
    "    shape = glue1.Shape()\n",
    "\n",
    "    display.SetModeHLR()\n",
    "\n",
    "    # move the glued shape, such to be able to inspect input and output\n",
    "    # of glueing operation\n",
    "    trsf = gp_Trsf()\n",
    "    trsf.SetTranslation(gp_Vec(500, 0, 0))\n",
    "    shape.Move(TopLoc_Location(trsf))\n",
    "\n",
    "    tag_faces(get_faces(shape), \"BLACK\", \"\")\n",
    "\n",
    "    # render glued shape\n",
    "    display.DisplayShape(shape)\n",
    "    display.FitAll()\n",
    "\n",
    "\n",
    "def glue_solids_edges(event=None):\n",
    "    display.EraseAll()\n",
    "    display.Context.RemoveAll()\n",
    "\n",
    "    # With common edges\n",
    "    S3 = BRepPrimAPI_MakeBox(500., 400., 300.).Shape()\n",
    "    S4 = BRepPrimAPI_MakeBox(gp_Pnt(0., 0., 300.), gp_Pnt(200., 200., 500.)).Shape()\n",
    "\n",
    "    faces_S3 = get_faces(S3)\n",
    "    faces_S4 = get_faces(S4)\n",
    "\n",
    "    # tagging allows to visually find the right faces to glue\n",
    "    tag_faces(faces_S3, \"BLUE\", \"s3\")\n",
    "    tag_faces(faces_S4, \"GREEN\", \"s4\")\n",
    "\n",
    "    F3, F4 = faces_S3[5], faces_S4[4]\n",
    "\n",
    "    glue2 = BRepFeat_Gluer(S4, S3)\n",
    "    glue2.Bind(F4, F3)\n",
    "    glue2.Build()\n",
    "    shape = glue2.Shape()\n",
    "\n",
    "    # move the glued shape, such to be able to inspect input and output\n",
    "    # of glueing operation\n",
    "    trsf = gp_Trsf()\n",
    "    trsf.SetTranslation(gp_Vec(750, 0, 0))\n",
    "    shape.Move(TopLoc_Location(trsf))\n",
    "\n",
    "    common_edges = LocOpe_FindEdges(F4, F3)\n",
    "    common_edges.InitIterator()\n",
    "\n",
    "    n = 0\n",
    "    while common_edges.More():\n",
    "        edge_from = common_edges.EdgeFrom()\n",
    "        edge_to = common_edges.EdgeTo()\n",
    "\n",
    "        tag_edge(edge_from, \"edge_{0}_from\".format(n))\n",
    "        tag_edge(edge_to, \"edge_{0}_to\".format(n))\n",
    "\n",
    "        glue2.Bind(edge_from, edge_to)\n",
    "        common_edges.Next()\n",
    "        n += 1\n",
    "\n",
    "    tag_faces(get_faces(shape), \"BLACK\", \"\")\n",
    "    display.FitAll()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    menu_name = 'glue topology'\n",
    "    add_menu(menu_name)\n",
    "    add_function_to_menu(menu_name, glue_solids)\n",
    "    add_function_to_menu(menu_name, glue_solids_edges)\n",
    "    # add_function_to_menu(menu_name, exit)\n",
    "    start_display()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
